//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class1.
    /// </summary>
    //  *** Start programmer edit section *** (NewClass1 CustomAttributes)

    //  *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [Caption("New class1")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass1E", new string[] {
            "NewClass2 as \'New class2\'"})]
    [View("NewClass1L", new string[0])]
    public class NewClass1 : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.test.NewClass2 fNewClass2;
        
        //  *** Start programmer edit section *** (NewClass1 CustomMembers)

        //  *** End programmer edit section *** (NewClass1 CustomMembers)

        
        /// <summary>
        /// New class1.
        /// </summary>
        //  *** Start programmer edit section *** (NewClass1.NewClass2 CustomAttributes)

        //  *** End programmer edit section *** (NewClass1.NewClass2 CustomAttributes)
        [NotNull()]
        public virtual IIS.test.NewClass2 NewClass2
        {
            get
            {
                //  *** Start programmer edit section *** (NewClass1.NewClass2 Get start)

                //  *** End programmer edit section *** (NewClass1.NewClass2 Get start)
                IIS.test.NewClass2 result = this.fNewClass2;
                //  *** Start programmer edit section *** (NewClass1.NewClass2 Get end)

                //  *** End programmer edit section *** (NewClass1.NewClass2 Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (NewClass1.NewClass2 Set start)

                //  *** End programmer edit section *** (NewClass1.NewClass2 Set start)
                this.fNewClass2 = value;
                //  *** Start programmer edit section *** (NewClass1.NewClass2 Set end)

                //  *** End programmer edit section *** (NewClass1.NewClass2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass1E", typeof(IIS.test.NewClass1));
                }
            }
            
            /// <summary>
            /// "NewClass1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass1L", typeof(IIS.test.NewClass1));
                }
            }
        }
    }
}
